name: Conditional Template Skip Deployment

on:
  pull_request:
    types: [opened, edited, reopened]
    branches:
      - dev
      - staging
      - preprod
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Parse PR Body and Check Deployment Flag
        id: parse_pr
        run: |
          # Extract the PR body
          PR_BODY=$(jq -r '.pull_request.body' < "$GITHUB_EVENT_PATH")
          echo "PR Body: $PR_BODY"

          # Parse the "skip deployment" flag
          SKIP_DEPLOYMENT=$(echo "$PR_BODY" | grep -oP '(?<=skip deployment: `)[^`]+')
          
          # Check if the skip deployment flag is set to 'Y'
          if [ "$SKIP_DEPLOYMENT" == "Y" ]; then
            echo "Deployment skipped based on PR template."
            echo "SKIP_DEPLOYMENT=true" >> $GITHUB_ENV
          else
            echo "Proceeding with deployment."
            echo "SKIP_DEPLOYMENT=false" >> $GITHUB_ENV
          fi

      - name: Validate PR Body (Always Run)
        run: |
          echo "Validating PR body and other necessary checks..."
          # Add other validation steps like checking for required fields, etc.

      - name: Deploy Dev Environment
        if: env.SKIP_DEPLOYMENT != 'true' && contains(github.event.pull_request.body, 'Dev Environment: `Y`')
        run: |
          echo "Deploying to Dev Environment..."
          # Add deployment steps here for Dev

      - name: Deploy Staging Environment
        if: env.SKIP_DEPLOYMENT != 'true' && contains(github.event.pull_request.body, 'Staging Environment: `Y`')
        run: |
          echo "Deploying to Staging Environment..."
          # Add deployment steps here for Staging

      - name: Deploy Preprod Environment
        if: env.SKIP_DEPLOYMENT != 'true' && contains(github.event.pull_request.body, 'Preprod Environment: `Y`')
        run: |
          echo "Deploying to Preprod Environment..."
          # Add deployment steps here for Preprod

      - name: Deploy Prod Environment
        if: env.SKIP_DEPLOYMENT != 'true' && contains(github.event.pull_request.body, 'Prod Environment: `Y`')
        run: |
          echo "Deploying to Prod Environment..."
          # Add deployment steps here for Prod

      - name: Final Validation (Always Run)
        run: |
          echo "Running final validations..."
          # Additional validations before completing the job.
